### PR TITLE
fix constact localization to contact

### PR DESCRIPTION
**Pull request by benwoody**
Simple update to fix a misspelling of `contact` as `constact`

### CODE REVIEW

**Comment by tmolitor-stud-tu** [comment]
Thanks, but this is the wrong repository for this.
The left side of the translation files are auto-generated from the source code in the https://github.com/monal-im/Monal repository. You'll have to search for the wrong string in that repository and create a pull request there.

Afterwards, the translators will pick up the new string and translate it again OR we could merge this PR to lift the burden of retranslation from our translators.

**Comment by benwoody** [comment]
@tmolitor-stud-tu Ahhh, sorry about that. I didn't see the translations in that repo, but the README there makes me think it's done on webplate? I found the misspelled strings here: https://hosted.weblate.org/search/monal/?q=constact&sort_by=-priority%2Cposition&checksum= but I'm not sure I have access to edit them.

I'll close this out if it's not needed.

**Comment by benwoody** [comment]
I think it was here: https://github.com/monal-im/Monal/commit/843c204ed653c40c0b43287c9ad9771445b88f53

**Comment by tmolitor-stud-tu** [comment]
Yes, translation is done with weblate, but the source what can be translated is automatically extracted from the source code on every beta build.

Yes, you found a commit already correcting the string in the source code.
It will be part of the next major version, so the translation will update automatically.

I'm closing this pr now, but anyway, thanks for your contribution :)

**Comment by benwoody** [comment]
Gotcha. Sorry for the run-around and thanks for Monal!

**Comment by tmolitor-stud-tu** [comment]
No problem, thanks for caring :)

**Pull request closed without merging**
